# Generated by Django 3.1.6 on 2023-03-01 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Positive'), (2, 'Neutral'), (3, 'Negative')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='source_stream',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Viator')], default=1),
            preserve_default=False,
        ),
    ]
