# Generated by Django 3.1.6 on 2023-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230301_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='source_stream',
            field=models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb')]),
        ),
    ]
