# Generated by Django 3.1.6 on 2023-03-07 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_review_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='source_stream',
            field=models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitas'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')]),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitas'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
