# Generated by Django 3.1.6 on 2023-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230308_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Positive'), (2, 'Neutral'), (3, 'Negative')], null=True),
        ),
    ]
