# Generated by Django 3.1.6 on 2023-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230308_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='places',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Positive'), (2, 'Neutral'), (1, 'Negative')], null=True),
        ),
    ]
