# Generated by Django 3.1.6 on 2023-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230308_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='can_respond',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='stream',
            field=models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitatis'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='source_stream',
            field=models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitatis'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')]),
        ),
    ]
