# Generated by Django 3.1.6 on 2023-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230322_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
