# Generated by Django 3.1.6 on 2023-05-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.PositiveSmallIntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitatis'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
