# Generated by Django 3.1.6 on 2023-06-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230531_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
