# Generated by Django 3.1.6 on 2023-06-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_apikeystream_credentialstream_urlstream'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='apikeystream',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'checking'), (3, 'wrong'), (4, 'correct')], default=1),
        ),
        migrations.AddField(
            model_name='credentialstream',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'checking'), (3, 'wrong'), (4, 'correct')], default=1),
        ),
        migrations.AddField(
            model_name='urlstream',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'checking'), (3, 'wrong'), (4, 'correct')], default=1),
        ),
        migrations.AlterField(
            model_name='apikeystream',
            name='source_stream',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='credentialstream',
            name='source_stream',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urlstream',
            name='source_stream',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Warning'), (3, 'Danger')])),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('client_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('schedule', models.TextField(null=True)),
                ('search_factor', models.PositiveSmallIntegerField(choices=[(0, 'Streams'), (1, 'Keywords'), (2, 'Countries'), (3, 'Tours')], null=True)),
                ('format', models.PositiveSmallIntegerField(choices=[(0, 'PDF'), (1, 'xlsx'), (2, 'xls')], null=True)),
                ('email_addresses', models.ManyToManyField(to='api.ScheduleEmailAddress')),
            ],
        ),
    ]
