# Generated by Django 3.1.6 on 2023-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230605_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportschedule',
            name='date_range_export',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Montly')], null=True),
        ),
    ]
