# Generated by Django 3.1.6 on 2023-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_exportschedule_date_range_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportschedule',
            name='schedule_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportschedule',
            name='search_factor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'source_stream'), (1, 'keywords'), (2, 'country_code'), (3, 'tours')], null=True),
        ),
    ]
