# Generated by Django 3.1.6 on 2023-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20230606_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Warning'), (3, 'Danger')], null=True),
        ),
    ]
