# Generated by Django 3.1.6 on 2023-06-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='client',
        ),
    ]
