# Generated by Django 3.1.6 on 2023-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230623_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_got_from',
            field=models.TextField(null=True),
        ),
    ]
