# Generated by Django 3.1.6 on 2023-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20230714_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Payed'), (1, 'Pending')], default=1),
        ),
    ]
