# Generated by Django 3.1.6 on 2023-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SMALL'), (1, 'MEDIUM'), (1, 'LARGE')], default=None, null=True),
        ),
    ]
