# Generated by Django 3.1.6 on 2023-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20230720_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
