# Generated by Django 3.1.6 on 2023-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20230720_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
