# Generated by Django 3.1.6 on 2023-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_payment_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeystream',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentialstream',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlstream',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
