# Generated by Django 3.1.6 on 2023-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20230911_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(unique=True, upload_to='stream_images')),
            ],
        ),
    ]
