# Generated by Django 3.1.6 on 2023-07-14 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20230630_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('related_users', models.ManyToManyField(blank=True, related_name='related_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
