# Generated by Django 3.1.6 on 2023-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20230714_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_ends',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
