# Generated by Django 3.1.6 on 2023-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_company_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE')], default=None, null=True),
        ),
    ]
