# Generated by Django 3.1.6 on 2023-08-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20230718_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
