# Generated by Django 3.1.6 on 2023-08-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_company_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='subscription_active',
            new_name='subscription_renewal',
        ),
    ]
