# Generated by Django 3.1.6 on 2023-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('in_use', models.BooleanField(default=False)),
                ('started_using', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
